author: H31IX
database: false
description: IP Security for your server.
main: net.h31ix.ipsecurity.IPSecurity
name: IPSecurity
startup: postworld
url: http://gravitydevelopment.net
version: '1.2'
commands:
  ips:
    description: Configure IPSecurity
